<script lang="ts">
  import Download from "@lucide/svelte/icons/download";
  import FileJson from "@lucide/svelte/icons/file-json";
  import ListMusic from "@lucide/svelte/icons/list-music";
  import Upload from "@lucide/svelte/icons/upload";
  import { getLocalization } from "$lib/i18n/translator.svelte";
  import { containMusicDialogFocus } from "$lib/music/music-dialog-focus";
  import type { MusicInterchangeController } from "$lib/music/music-interchange-controller.svelte";
  import type { MusicPlaylistSummary } from "$lib/music/library-contracts";

  let { controller, playlists, onClose, onImported }: { controller: MusicInterchangeController; playlists: MusicPlaylistSummary[]; onClose: () => void; onImported: () => void } = $props();
  const { t } = getLocalization();
  const preview = $derived(controller.jsonPreview);
  const m3u = $derived(controller.m3u8Preview);
  const missingRoots = $derived(preview?.document.roots.filter((root) => !controller.isRootMapped(root.id)) ?? []);

  async function commit(): Promise<void> {
    if (await controller.commitImport()) onImported();
  }
</script>

<div class="absolute inset-0 z-60 grid place-items-center bg-background/65 p-3 backdrop-blur-sm">
  <div use:containMusicDialogFocus={{ onEscape: onClose, escapeDisabled: controller.busy }} role="dialog" aria-modal="true" aria-labelledby="music-interchange-title" tabindex="-1" class="flex max-h-full w-full max-w-2xl flex-col overflow-hidden rounded-2xl border border-border/70 bg-card shadow-2xl">
    <header class="flex shrink-0 items-center gap-3 border-b border-border/60 p-4"><span class="grid h-10 w-10 place-items-center rounded-xl bg-primary/10 text-primary">{#if controller.mode === "export"}<Download size={18} />{:else}<Upload size={18} />{/if}</span><div><h2 id="music-interchange-title" class="text-sm font-semibold">{controller.mode === "export" ? t("music.builder.exportPlaylists") : t("music.builder.importPlaylists")}</h2><p class="mt-0.5 text-[0.68rem] text-muted-foreground">{controller.mode === "export" ? t("music.builder.exportPlaylistsHint") : t("music.builder.importPlaylistsHint")}</p></div></header>
    <div class="min-h-0 overflow-y-auto p-4" data-music-scrollable="true">
      {#if controller.importResult}
        <div class="rounded-xl border border-success/25 bg-success/8 p-4"><h3 class="text-sm font-semibold text-success">{t("music.builder.importComplete")}</h3><p class="mt-1 text-xs text-muted-foreground">{t("music.builder.importCompleteCounts", controller.importResult.playlistCount, controller.importResult.itemCount, controller.importResult.membershipCount)}</p></div>
      {:else if controller.mode === "export"}
        <div class="grid grid-cols-1 gap-2 min-[420px]:grid-cols-2"><button type="button" aria-pressed={controller.format === "json"} onclick={() => controller.format = "json"} class="format-card"><FileJson size={17} /><span><strong>{t("music.builder.ganbaruJson")}</strong><small>{t("music.builder.ganbaruJsonHint")}</small></span></button><button type="button" aria-pressed={controller.format === "m3u8"} onclick={() => controller.format = "m3u8"} class="format-card"><ListMusic size={17} /><span><strong>M3U8</strong><small>{t("music.builder.m3u8Hint")}</small></span></button></div>
        {#if controller.format === "m3u8"}<p class="mt-3 rounded-lg border border-warning/20 bg-warning/8 p-2.5 text-[0.66rem] leading-relaxed text-muted-foreground">{t("music.builder.m3u8LossWarning")}</p>{/if}
        <div class="mt-4 flex items-center justify-between"><h3 class="text-xs font-semibold">{t("music.builder.choosePlaylists")}</h3><button type="button" onclick={() => controller.selectedPlaylistIds = new Set(playlists.map((playlist) => playlist.id))} class="text-[0.65rem] text-primary hover:underline">{t("music.builder.selectAll")}</button></div>
        <div class="mt-2 grid gap-1.5 sm:grid-cols-2">{#each playlists as playlist}<label class="flex min-w-0 items-center gap-2 rounded-lg border border-border/55 bg-background/45 p-2.5 text-xs"><input type="checkbox" checked={controller.selectedPlaylistIds.has(playlist.id)} onchange={() => controller.togglePlaylist(playlist.id)} class="accent-primary" /><span class="min-w-0 flex-1 truncate">{playlist.name}</span><span class="text-[0.62rem] text-muted-foreground">{playlist.totalCount}</span></label>{/each}</div>
      {:else if !preview && !m3u}
        <div class="grid min-h-52 place-items-center rounded-xl border border-dashed border-border/70 p-6 text-center"><div><Upload class="mx-auto text-muted-foreground" size={25} /><h3 class="mt-3 text-sm font-semibold">{t("music.builder.chooseImportFile")}</h3><p class="mx-auto mt-1 max-w-sm text-xs leading-relaxed text-muted-foreground">{t("music.builder.chooseImportFileHint")}</p><button type="button" onclick={() => { void controller.readImport(); }} disabled={controller.busy} class="mt-4 h-9 rounded-lg bg-primary px-4 text-xs font-semibold text-primary-foreground disabled:opacity-50">{t("music.builder.browseFiles")}</button></div></div>
      {:else if preview}
        <div class="grid grid-cols-2 gap-2 sm:grid-cols-3"><div class="preview-stat"><strong>{preview.newPlaylists}</strong><span>{t("music.builder.newPlaylists")}</span></div><div class="preview-stat"><strong>{preview.matchedItems}</strong><span>{t("music.builder.matchedItems")}</span></div><div class="preview-stat"><strong>{preview.newItems}</strong><span>{t("music.builder.newItems")}</span></div><div class="preview-stat"><strong>{preview.duplicateItems}</strong><span>{t("music.builder.duplicateItems")}</span></div><div class="preview-stat"><strong>{preview.missingLocalBindings}</strong><span>{t("music.builder.unmappedRoots")}</span></div><div class="preview-stat"><strong>{preview.unsupported.length}</strong><span>{t("music.builder.unsupportedEntries")}</span></div></div>
        {#if preview.unsupported.length > 0}<div class="mt-3 max-h-24 overflow-y-auto rounded-lg bg-warning/8 p-2 text-[0.63rem] leading-relaxed text-muted-foreground">{#each preview.unsupported as issue}<p>{issue}</p>{/each}</div>{/if}
        {#if preview.conflicts.length > 0}<div class="mt-4"><label class="text-[0.68rem] font-semibold" for="music-import-conflicts">{t("music.builder.playlistConflictDecision")}</label><select id="music-import-conflicts" bind:value={controller.playlistConflict} class="mt-1.5 h-9 w-full rounded-lg border border-border/70 bg-background px-2 text-xs"><option value="import-copy">{t("music.builder.importAsCopy")}</option><option value="keep-existing">{t("music.builder.keepExisting")}</option><option value="replace-existing">{t("music.builder.replaceExisting")}</option></select><p class="mt-1 text-[0.63rem] text-muted-foreground">{preview.conflicts.join(", ")}</p></div>{/if}
        {#if missingRoots.length > 0}<div class="mt-4"><h3 class="text-xs font-semibold">{t("music.builder.mapImportedRoots")}</h3><p class="mt-1 text-[0.65rem] leading-relaxed text-muted-foreground">{t("music.builder.mapImportedRootsHint")}</p><div class="mt-2 space-y-1.5">{#each missingRoots as root}<div class="flex items-center gap-2 rounded-lg bg-secondary/50 p-2"><span class="min-w-0 flex-1 truncate text-xs">{root.name}</span><button type="button" onclick={() => { void controller.mapImportedRoot(root.id); }} class="h-7 rounded-md bg-background px-2 text-[0.65rem] font-medium">{controller.mappedRootIds.has(root.id) ? t("music.builder.rootMapped") : t("music.builder.chooseFolder")}</button></div>{/each}</div></div>{/if}
        <div class="mt-4 space-y-2"><label class="flex items-start gap-2 text-[0.68rem]"><input type="checkbox" bind:checked={controller.replaceItemDescriptions} class="mt-0.5 accent-primary" /><span>{t("music.builder.replaceImportedDescriptions")}</span></label>{#if preview.document.contextAssignments.length > 0}<label class="flex items-start gap-2 text-[0.68rem]"><input type="checkbox" bind:checked={controller.importContextAssignments} class="mt-0.5 accent-primary" /><span>{t("music.builder.importAssignments", preview.document.contextAssignments.length)}</span></label>{/if}</div>
      {:else if m3u}
        <p class="rounded-lg border border-warning/20 bg-warning/8 p-2.5 text-[0.66rem] leading-relaxed text-muted-foreground">{t("music.builder.m3u8LossWarning")}</p>
        <div class="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4"><div class="preview-stat"><strong>{m3u.localCount}</strong><span>{t("music.builder.local")}</span></div><div class="preview-stat"><strong>{m3u.youtubeCount}</strong><span>{t("music.builder.youtube")}</span></div><div class="preview-stat"><strong>{controller.unresolvedM3uCount()}</strong><span>{t("music.builder.unresolvedPaths")}</span></div><div class="preview-stat"><strong>{m3u.unsupportedCount}</strong><span>{t("music.builder.unsupportedEntries")}</span></div></div>
        <label class="mt-4 block text-[0.68rem] font-semibold" for="music-m3u-name">{t("music.builder.playlistName")}</label><input id="music-m3u-name" bind:value={controller.importPlaylistName} class="mt-1.5 h-9 w-full rounded-lg border border-border/70 bg-background px-3 text-xs" />
        <label class="mt-3 block text-[0.68rem] font-semibold" for="music-m3u-root">{t("music.builder.relativePathRoot")}</label><select id="music-m3u-root" bind:value={controller.m3u8RootId} class="mt-1.5 h-9 w-full rounded-lg border border-border/70 bg-background px-2 text-xs"><option value="">{t("music.builder.noRootSelected")}</option>{#each controller.availableRoots as root}<option value={root.id}>{root.name}</option>{/each}</select><p class="mt-1 text-[0.63rem] text-muted-foreground">{t("music.builder.relativePathRootHint")}</p>
      {/if}
      {#if controller.error}<p class="mt-3 rounded-lg bg-destructive/8 p-2.5 text-[0.68rem] text-destructive" role="alert">{controller.error}</p>{/if}
    </div>
    <footer class="flex shrink-0 flex-wrap justify-end gap-2 border-t border-border/60 p-3"><button type="button" onclick={onClose} disabled={controller.busy} class="h-8 rounded-md bg-secondary px-3 text-xs font-medium disabled:opacity-50">{controller.importResult ? t("music.builder.close") : t("music.builder.cancel")}</button>{#if controller.mode === "export"}<button type="button" onclick={() => { void controller.exportSelected(); }} disabled={controller.busy || controller.selectedPlaylistIds.size === 0} class="h-8 rounded-md bg-primary px-3 text-xs font-semibold text-primary-foreground disabled:opacity-50">{controller.busy ? t("music.builder.exporting") : t("music.builder.exportPlaylists")}</button>{:else if (preview || m3u) && !controller.importResult}<button type="button" onclick={() => { void commit(); }} disabled={controller.busy || (Boolean(m3u) && !controller.importPlaylistName.trim())} class="h-8 rounded-md bg-primary px-3 text-xs font-semibold text-primary-foreground disabled:opacity-50">{controller.busy ? t("music.builder.importing") : t("music.builder.importPlaylists")}</button>{/if}</footer>
  </div>
</div>

<style>
  .format-card { display: flex; min-width: 0; align-items: flex-start; gap: 0.65rem; border: 1px solid color-mix(in srgb, var(--border) 70%, transparent); border-radius: 0.75rem; padding: 0.75rem; text-align: left; }
  .format-card[aria-pressed="true"] { border-color: color-mix(in srgb, var(--primary) 65%, var(--border)); background: color-mix(in srgb, var(--primary) 8%, transparent); }
  .format-card span { min-width: 0; } .format-card strong { display: block; font-size: 0.75rem; } .format-card small { margin-top: 0.2rem; display: block; color: var(--muted-foreground); font-size: 0.62rem; line-height: 1.35; }
  .preview-stat { border-radius: 0.7rem; background: color-mix(in srgb, var(--secondary) 68%, transparent); padding: 0.65rem; } .preview-stat strong { display: block; font-size: 1rem; } .preview-stat span { display: block; color: var(--muted-foreground); font-size: 0.62rem; }
</style>
